---
title: "wk3 scratch"
author: "Phil Callahan"
date: "2/12/2021"
output: pdf_document
---

# Generalized Linear Models: Logistic Regression and ROC Curves

```{r}
#regress Weight with rest of preds - must run ANN Rmd for HJ first
#regress height and weight on each other ----------------------------------------
fit_Weight <- lm(Weight ~ Height + Team + Year, data=finalHJ)
finalHJ$Weight_resid <- fit_Weight$residuals
finalHJ

```


```{r, warning=FALSE}
#logreg fit model with 3 vars - be sure you run ann_olympic
fitLR_HJ = glm(binMedal ~ Age + Height + Weight_resid + Team + Year,
          data=finalHJ, family=binomial)

summary(fitLR_HJ)
```
*we can see from the p-val that weight is not a significant variable, therefore we can exclude it in ANN*


```{r}
finalHJ$binMedal <- factor(finalHJ$binMedal)
```

```{r}
#setup CV params ===================================
nLR=dim(finalHJ)[1] #num of observations
kLR=10 #using 10-fold cross-validation
groupsLR = c(rep(1:kLR,floor(nLR/kLR)*kLR))
set.seed(123)
cvgroupsLR = sample(groupsLR, nLR) #place observations in random groups

#first fit =======================================================
predictvalsLR1 = rep(-1,nLR) #makes troubleshooting easier
# predictvals #test print
for(iLR1 in 1:kLR){
  groupiLR1 = (cvgroupsLR==iLR1) #all obs in each group created previously
  fitLR1 = glm(binMedal ~ Year,
            data=finalHJ[groupiLR1,], family="binomial")
  predictvalsLR1[groupiLR1] = predict(fitLR1, finalHJ[groupiLR1,],
                                type="response")
}
```

```{r}
#slide13
predictvalsLR1[1:3] #returns predicted probabilities
conMatLR1 <- addmargins(table(predictvalsLR1 > 0.5, finalHJ$binMedal))
conMatLR1

misclassLR1 = (conMatLR1[1,2] + conMatLR1[2,1])/conMatLR1[3,3]
cat("\nmisclassification rate for fitLR:", misclassLR1)
```

```{r, warning=F, fig.height=5.5, fig.width=6}


#model 2 middle model ============================================
predictvalsLR2 = rep(-1,nLR) #makes troubleshooting easier
for(iLR2 in 1:kLR){
  groupiLR2 = (cvgroupsLR==iLR2) #all obs in each group created previously
  fitLR2 = glm(binMedal ~ Age+ Height + Weight_resid + Year,
            data=finalHJ[groupiLR2,], family="binomial")
  predictvalsLR2[groupiLR2] = predict(fitLR2, finalHJ[groupiLR2,],
                                type="response")
}

#model 3 most variables ==========================================
predictvalsLR3 = rep(-1,nLR) #makes troubleshooting easier
for(iLR3 in 1:kLR){
  groupiLR3 = (cvgroupsLR==iLR3) #all obs in each group created previously
  fitLR3 = glm(binMedal ~ Age + Height + Weight_resid + Team + Year,
            data=finalHJ[groupiLR3,], family="binomial")
  predictvalsLR3[groupiLR3] = predict(fitLR3, finalHJ[groupiLR3,],
                                type="response")
}

#LR model1, fewest variables ---------
library(pROC) #library to get ROC curve
myrocLR1 = roc(response=finalHJ$binMedal, predictor=predictvalsLR1)
plot.roc(myrocLR1, col="firebrick", lty=3, lwd=3)
#LR model2 ---------------
myrocLR2 = roc(response=finalHJ$binMedal, predictor=predictvalsLR2)
plot.roc(myrocLR2, add=T, col="goldenrod4", lty=4, lwd=3)
#LR model3 -------------
myrocLR3 = roc(response=finalHJ$binMedal, predictor=predictvalsLR3)
plot.roc(myrocLR3, add=T, col="cadetblue", lty=2, lwd=3)

# # example of filled polygon
# myrocLRhjF1 = roc(response=finalHJf$Medal01, predictor=predictvalsLRhjF1)
# plot.roc(myrocLRhjF1, add=T, col="firebrick", lty=3, auc.polygon = TRUE, 
#     auc.polygon.col="lightpink",
#     auc.polygon.border=rgb(0,0,0, alpha=0))

legend("bottomright", legend=c("Age + Height + Weight_resid + Team + Year",
                               "Age + Height + Weight_resid + Year",
                               "Year"),
       lty=c(2,4,3), lwd=3, col=c("cadetblue", "goldenrod4", "firebrick"))
title("ROC Curve for High Jump Predictors")

#AUCs ======================
text(.8, .88, paste0("AUC:\n", round(auc(myrocLR3),2)), col="cadetblue", cex=1.2)
text(.55, .8, paste0("AUC:\n", round(auc(myrocLR2),2)), col="goldenrod4", cex=1.2)
text(.3, .77, paste0("AUC:\n", round(auc(myrocLR1),2)),col="firebrick", cex=1.2)
auc(myrocLR1)
auc(myrocLR2)
auc(myrocLR3)
```

```{r}
#compare second model performance with three predictors
#slide13
predictvalsLR2[1:3] #returns predicted probabilities
conMatLR2 <- addmargins(table(predictvalsLR2 > 0.5, finalHJ$binMedal))
conMatLR2

misclassLR2 = (conMatLR2[1,2] + conMatLR2[2,1])/conMatLR2[3,3]
cat("\nmisclassification rate:", misclassLR2)
```
*best performer for HJ model*
```{r}
#compare second model performance with three predictors
#slide13
predictvalsLR3[1:3] #returns predicted probabilities
conMatLR3 <- addmargins(table(predictvalsLR3 > 0.5, finalHJ$binMedal))
conMatLR3

misclassLR3 = (conMatLR3[1,2] + conMatLR3[2,1])/conMatLR3[3,3]
cat("\nmisclassification rate:", misclassLR3)
cat("\nLR Model 3 Accuracy Rate:",round((1-misclassLR3)*100,2),"%")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

```{r}

```





