---
title: "Swimming Log Reg"
author: "Phil Callahan"
date: "4/30/2021"
output: pdf_document
---
```{r, warning=F}
olympic <- read.csv("olympic_data.csv")
olympic
```

```{r, warning=F}
#separate swimmers ------------------------------------------
allSwimmers <- olympic[which(olympic$Sport == "Swimming"),]
allSwimmers

#separate male swimmers ------------------------------------------
Mswimmers <- allSwimmers[which(grepl("Swimming Men's", allSwimmers$Event, fixed=TRUE) == TRUE),]
Mswimmers
#separate female swimmers ----------------------------------------
Fswimmers <- allSwimmers[which(grepl("Swimming Women's", allSwimmers$Event, fixed=TRUE) == TRUE),]
Fswimmers
```

```{r, warning=F}
#test to see if select for specifc string
olympic[which(grepl("Men's", olympic$Event, fixed = TRUE) == TRUE),]

```

```{r, warning=F}
#add binary Medal column
dummyMswim <- Mswimmers
dummyMswim$Medal = factor(dummyMswim$Medal)
dummyMswim$binMedal <- ifelse(is.na(dummyMswim$Medal), 0, 1)
dummyMswim
```

```{r, warning=F}
finalMswim <- dummyMswim[,-which(names(dummyMswim) %in% 
                                c("ID", "Name", "Sex", "Games",
                                  "NOC", "Games", "Season", "Sport",
                                  "Medal"))]
finalMswim <- na.omit(finalMswim) #get rid of the rows with NA

finalMswim
```

```{r, warning=FALSE}
#logreg fit model 
fitLRall = lm(binMedal ~ .,
          data=finalMswim, family=binomial)
options(max.print = 9999)
summary(fitLRall)
```

#after exploring the data, I tried fit after getting rid of relays and all events with "Yard" (switched to meters after 1904) since they can falsely weight results (e.g. New York Athletic Club)
```{r}
#remove relay events
noRelayMswim <- finalMswim[which(grepl("Relay", finalMswim$Event, fixed=TRUE) == FALSE),]
metersOnlyMswim <- noRelayMswim[which(grepl("yard", noRelayMswim$Event, fixed=TRUE) == FALSE),]

metersOnlyMswim
```

```{r}
#refit with significant vars
refitLR1 <- lm(binMedal ~ .,
          data=metersOnlyMswim, family=binomial)
options(max.print = 9999)
summary(refitLR1)
```

```{r}
#factorize everything
metersOnlyMswim$Team = factor(metersOnlyMswim$Team)
metersOnlyMswim$City = factor(metersOnlyMswim$City)
metersOnlyMswim$Event = factor(metersOnlyMswim$Event)
metersOnlyMswim
```
```{r}
pairs(metersOnlyMswim)
```
```{r}
#regress height and weight on each other ----------------------------------------
fit_Weight <- lm(Weight ~ Height + Team + Year, data=metersOnlyMswim)
metersOnlyMswim$Weight_resid <- fit_Weight$residuals
metersOnlyMswim
```
```{r}
#check new df for multicollinearity
pairs(metersOnlyMswim)
```

```{r}
#final fit
refitLR2 <- glm(binMedal ~ Height + Weight_resid + Team + Year,
          data=metersOnlyMswim, family=binomial)
options(max.print = 9999)
summary(refitLR2)
```
```{r}
#test models to fit
refitLR3 <- glm(binMedal ~ Height + Weight_resid + Year,
          data=metersOnlyMswim, family=binomial)
# options(max.print = 9999)
summary(refitLR3)
```

```{r}
#slide11-12
nLR=dim(metersOnlyMswim)[1] #num of observations
kLR=10 #using 10-fold cross-validation
groupsLR = c(rep(1:kLR,floor(nLR/kLR)*kLR))
set.seed(123)
cvgroupsLR = sample(groupsLR, nLR) #place observations in random groups
predictvalsLR4 = rep(-1,nLR) #makes troubleshooting easier

# predictvals #test print
for(iLR in 1:kLR){
  groupiLR = (cvgroupsLR==iLR) #all obs in each group created previously
  fitLR4 = glm(binMedal ~ Year,
            data=metersOnlyMswim[groupiLR,], family="binomial")
  predictvalsLR4[groupiLR] = predict(fitLR4, metersOnlyMswim[groupiLR,],
                                type="response")
}
```

```{r, warning=F}

#create a 2nd swimmer model to compare ROCs ----------------------------------
predictvalsLR5 = rep(-1,nLR) #makes troubleshooting easier
for(iLR in 1:kLR){
  groupiLR5 = (cvgroupsLR==iLR) #all obs in each group created previously
  fitLR5 = glm(binMedal ~ Age + Height + Weight_resid + Year,
            data=metersOnlyMswim[groupiLR5,], family="binomial")
  predictvalsLR5[groupiLR5] = predict(fitLR5, metersOnlyMswim[groupiLR5,],
                                type="response")
}
```

```{r}
#create a 3rd swimmer model to compare ROCs ----------------------------------
predictvalsLR6 = rep(-1,nLR) #makes troubleshooting easier
for(iLR in 1:kLR){
  groupiLR6 = (cvgroupsLR==iLR) #all obs in each group created previously
  fitLR6 = glm(binMedal ~ Age + Height + Weight_resid + Year + Team,
            data=metersOnlyMswim[groupiLR6,], family="binomial")
  predictvalsLR6[groupiLR6] = predict(fitLR6, metersOnlyMswim[groupiLR6,],
                                type="response")
}
```

```{r, fig.height=5.5, fig.width=6}
#plot the models
#LR model4, fewest variables ---------
library(pROC) #library to get ROC curve
myrocLR4 = roc(response=metersOnlyMswim$binMedal, predictor=predictvalsLR4)
plot.roc(myrocLR4, col="firebrick", lty=3)
#LR model5 ---------------
myrocLR5 = roc(response=metersOnlyMswim$binMedal, predictor=predictvalsLR5)
plot.roc(myrocLR5, add=T, col="goldenrod4", lty=4)
#LR model6 ---------------
myrocLR6 = roc(response=metersOnlyMswim$binMedal, predictor=predictvalsLR6)
plot.roc(myrocLR6, add=T, col="cadetblue", lty=2)

legend("bottomright", legend=c("Age + Height + Weight_resid + Team + Year",
                               "Age + Height + Weight_resid + Year",
                               "Year"),
       lty=c(2,4,3), lwd=2, col=c("cadetblue", "goldenrod4", "firebrick"))
title("ROC Curve for Swimming Predictors")

#AUCs ======================
text(.68, .82, paste0("AUC:\n", round(auc(myrocLR6),2)), col="cadetblue", cex=1.2)
text(0.5, .68, paste0("AUC:\n", round(auc(myrocLR5),2)), col="goldenrod4", cex=1.1)
# segments(0.2,0.76,0.5,0.73, lwd=2, col="goldenrod4")
text(.3, .66, paste0("AUC:\n", round(auc(myrocLR4),2)),col="firebrick", cex=1.2)
# auc(myrocLR6)
# auc(myrocLR5)
# auc(myrocLR4)
```



```{r}
#first swim model, won't compute with only Year as predictor because no predicted medalers--------------------
# predictvalsLR4[1:3] #returns predicted probabilities
# conMatLR4 <- addmargins(table(predictvalsLR4 > 0.5, metersOnlyMswim$binMedal))
# conMatLR4
# 
# misclassLR4 = (conMatLR4[1,2] + conMatLR4[2,1])/conMatLR4[3,3]
# cat("\nmisclassification rate of modelLR4:", misclassLR4)

#compare second model performance with four predictors ------------------
# predictvalsLR5[1:3] #returns predicted probabilities
conMatLR5 <- addmargins(table(predictvalsLR5 > 0.5, metersOnlyMswim$binMedal))
conMatLR5

misclassLR5 = (conMatLR5[1,2] + conMatLR5[2,1])/conMatLR5[3,3]
cat("\nmisclassification rate of modelLR5:", misclassLR5)

#compare third model performance with 5 predictors ------------------
# predictvalsLR6[1:3] #returns predicted probabilities
conMatLR6 <- addmargins(table(predictvalsLR6 > 0.5, metersOnlyMswim$binMedal))
conMatLR6

misclassLR6 = (conMatLR6[1,2] + conMatLR6[2,1])/conMatLR6[3,3]
cat("\nmisclassification rate of modelLR6:", misclassLR6)
```
*best performer for Swimmer Model*

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

```{r, warning=F}

```

